site_name: Post Event Messaging Info
theme: bootstrap
pages:
  - Home: index.md
  - Help Guides:
    - Configuring GP Systems for ITK: guides/configuring_gp_systems.md
  - Contractual Guidance: StandardContractExtract2015.md
  - Clinical Guidance: clinical_faq.md
  - Frequently Asked Questions:
    - Operational: operational_faq.md
    - Technical: technical_faq.md
  - Glossary Of Terms: glossary.md
